services:
  server:
    build:
      context: .
    image: debian-server.taile49fd9.ts.net:81/dev/ct-backend:latest
    container_name: ct-backend-dev
    restart: always
    ports:
      - 8889:8889
    env_file:
      - .env.dev

